name = "fplot"
version = "1.7.2"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2017-2024, Jason Christopherson"
description = "A Fortran library providing a convenient interface for plotting with Gnuplot."
homepage = "https://github.com/jchristopherson/fplot"

[library]
source-dir = "src"

[dependencies]
ferror = { git = "https://github.com/jchristopherson/ferror" }
collections = { git = "https://github.com/jchristopherson/collections" }
fstring = { git = "https://github.com/jchristopherson/fstring" }
geompack = { git = "https://github.com/jchristopherson/geompack" }
forcolormap = { git = "https://github.com/vmagnin/forcolormap" }

[dev-dependencies]
fortran_test_helper = { git = "https://github.com/jchristopherson/fortran_test_helper" }

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "fplot_test"
source-dir = "test"
main = "fplot_test.f90"